# Generated by Django 3.2.8 on 2021-10-29 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredients',
            name='amount',
        ),
    ]
