# Generated by Django 3.2.8 on 2021-10-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_remove_recipeingredients_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeIngredients',
        ),
    ]
