version: '3.9'

services:
  web:
    build: .
    restart: always
    container_name: web
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - 8000:8000
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgres/data

volumes:
  pgdata: