# Generated by Django 3.2.8 on 2021-10-31 14:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='all_time',
            field=models.CharField(max_length=20, verbose_name='Общее время для приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, max_length=600, verbose_name='Краткое описание рецепта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(max_length=40, verbose_name='Название рецепта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_to_cook',
            field=ckeditor.fields.RichTextField(max_length=2000, verbose_name='Рецепт для готовки'),
        ),
    ]
