# Generated by Django 3.2.8 on 2021-10-31 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='account',
            new_name='author',
        ),
    ]
