# Generated by Django 3.2.8 on 2021-11-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_alter_ingredient_slug'),
        ('recipes', '0006_auto_20211101_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='complexity',
            field=models.CharField(blank=True, choices=[('Лёгкая', 'Легкая'), ('Средняя', 'Средняя'), ('Тяжёлая', 'Тяжелая')], max_length=20, verbose_name='Сложность готовки'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', to='ingredients.Ingredient', verbose_name='Ингредиенты продукта'),
        ),
    ]
